<?php
/* @var Magento\Framework\View\Element\Template $block */
/* @var Squeezely\Plugin\ViewModel\PixelManager $viewModel */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isEnabled()): ?>
    <!-- Squeezely Pixel  -->
    <script>
        (function(s,q,z,l,y){s._sqzl=s._sqzl||[];l=q.createElement('script'),
            y=q.getElementsByTagName('script')[0];l.async=1;l.type='text/javascript';
            l.defer=true;l.src=z;y.parentNode.insertBefore(l,y)})
        (window,document, '<?= /* @noEscape */ $viewModel->getJsLink();?>');
        window._sqzl = _sqzl || [];
        window._sqzl.push({
            "event": "PageView",
            "language": "<?= /* @noEscape */ $viewModel->getStoreLocale(); ?>"
        });

        if (!sessionStorage.getItem("new-session")) {
            window._sqzl.push({
                "event": "UpdateCart",
                "set_cart": true,
                "products": []
            });

            sessionStorage.setItem("new-session", "true");
        }
    </script>

    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "squeezely-cart": {
                            "component": "Squeezely_Plugin/js/cart-event-extend",
                            "trackAddToCart": <?= /* @noEscape */ $viewModel->trackAddToCart() ?>
                        }
                    }
                }
            }
        }
    </script>
    <!-- End Squeezely Pixel -->
<?php endif;?>
