<?php
$sqzlyId = $block->getSQZLYId();
?>
    <!-- Squeezely Pixel  -->

    <script type="text/javascript">

        (function(s,q,z,l,y){s._sqzl=s._sqzl||[];l=q.createElement('script'),
            y=q.getElementsByTagName('script')[0];l.async=1;l.type='text/javascript';
            l.defer=true;l.src=z;y.parentNode.insertBefore(l,y)})
        (window,document,'https://squeezely.tech/tracker/<?php echo $sqzlyId; ?>/sqzl.js'); // TODO REMOVE FIXED URL

        window._sqzl = _sqzl || [];
        window._sqzl.push({"event": "PageView"});

        require.config({
            deps: [
                'jquery',
                'mage/translate',
                'jquery/jquery-storageapi'
            ],
            callback: function ($) {
                'use strict';

                $(document).on("ajax:addToCart", function (event, data) {
                    var products = [{"id": data.sku}];
                    _sqzl.push({"event": "AddToCart", "products": products});
                });

            }
        });

    </script>

    <!-- End Squeezely Pixel -->

<?php
echo $block->getCurrentCategory();
echo $block->getDataLayerProduct();
echo $block->getDataLayerOrder();
?>