<?php
/* @var Magento\Framework\View\Element\Template $block */
/* @var Squeezely\Plugin\ViewModel\PixelManager $viewModel */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->isEnabled()): ?>
    <!-- Squeezely Pixel  -->
    <script type="text/javascript">
        (function(s,q,z,l,y){s._sqzl=s._sqzl||[];l=q.createElement('script'),
            y=q.getElementsByTagName('script')[0];l.async=1;l.type='text/javascript';
            l.defer=true;l.src=z;y.parentNode.insertBefore(l,y)})
        (window,document, '<?= /* @noEscape */ $viewModel->getJsLink();?>');

        window._sqzl = _sqzl || [];
    </script>
    <?= /* @noEscape */ $viewModel->fireQueuedEvents();?>
    <!-- End Squeezely Pixel -->
<?php endif;?>
