<?php
/**
 * Copyright © Squeezely B.V. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var Squeezely\Plugin\Block\Adminhtml\System\Design\BackendQueue $block
 */
$element = $block->getElement();
?>
<tr id="row_<?= /* @noEscape */ $element->getHtmlId() ?>">
    <td class="label"><?= /* @noEscape */ $element->getLabel() ?></td>
    <td class="value">
        <table class="mm-ui-table" border="1">
            <thead>
            <tr>
                <th><?= $block->escapeHtml(__('Totals')); ?></th>
                <th><?= $block->escapeHtml(__('Actions')); ?></th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <p><?= $block->escapeHtml($block->getNumberOfRecords()); ?></p>
                    </td>
                    <td>
                        <p>
                            <a href="<?= $block->escapeUrl($block->getProcessQueueUrl()) ?>">
                                <?= $block->escapeHtml(__('Run Now')); ?>
                            </a>
                        </p>
                    </td>
                </tr>
            </tbody>
        </table>
    </td>
    <td></td>
</tr>

