<!--
/**
 * Copyright © Squeezely B.V. All rights reserved.
 * See COPYING.txt for license details.
 */
-->

<div class="squeezely-header">
    <img src="https://squeezely.tech/build/logo.7a409ae091174c53e36b5e7d46002dab.png">
    <p>The Squeezely Magento 2 plugin is created to collect data from your Magento 2 store. After installing the plugin
        the following data will be synced to your Squeezely account: website events, store purchases & your product
        catalog.</p>
    <a class="docs" href="#">Documentation</a>
    <a class="support" href="#">Support</a>
    <a class="api" target="_blank" href="https://squeezely.tech/company/settings">Get API Details</a>
</div>
<div class="squeezely-header-developed">
    <p style="background-image: url(<?= $block->escapeUrl($block->getImage()); ?>)"></p>
    <p><strong>This extension is developed by <a href="https://www.magmodules.eu/"
                                                 target="_blank">Magmodules</a>.</strong>A Magento only eCommerce Agency
        located in the
        Netherlands.
    </p>
</div>
